apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galaxy-digital-pvc
  namespace: galaxy-digital
  labels:
    app: galaxy-digital
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
